# Generated by Django 2.1.4 on 2019-01-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='amount',
        ),
    ]
